### ISSUE TITLE
why your training datasets need stereo images (left and right views of scenes) ?

### ISSUE THREAD

**Issue by TuringKi** [visinf/multi-mono-sf#2]
From the figure 1. (in your paper):
![image](https://user-images.githubusercontent.com/9394223/117769413-4640eb00-b266-11eb-9ebe-8c6e62bd5b7a.png)

I does not get where you use the stereo images. and your evaluation code does not use them (the davis dataset...)

And can I do self-supervised training without stereo images? Since many wild datasets (open world dataset) do not have them.

**Comment by hurjunhwa** [comment]
Hi,

That's a really good question.

Yes, we use the stereo images only for training (specifically when calculating the proxy loss for disparity map), following the approach from [monodepth](https://github.com/mrharicot/monodepth).

The main advantages are that 
  - it outputs depth in an absolute scale (instead of an arbitrary scale from other approaches using monocular images for training) -> no need to properly scale in the test time.
  - it doesn't need to estimate ego-motion + moving object handling -> thus it makes the proxy loss much simpler & training more stable.

However, of course as a drawback, it requires stereo pairs for training which is not always available as in many cases.

Maybe you can refer [this work](https://arxiv.org/pdf/2010.16404.pdf) that uses monocular videos for training and estimates 3D motion.
