### ISSUE TITLE
I have question about depth metric

### ISSUE THREAD

**Issue by russellgeum** [visinf/multi-mono-sf#6]
Your research is so interesting. (selfmono-sf and multimono-sf)
Your depth metric does not computing median scaling.
But, another KITTI depth estimation model, monodepth2 uses median scaling computation

Why is there a difference in the metric computation method?

Your code 
multimono-sf
https://github.com/visinf/self-mono-sf/blob/054df08674a2df96885682e657ca4803c129a364/losses.py#L402
selfmono-sf
https://github.com/visinf/multi-mono-sf/blob/main/losses.py#L513

Monodepth2 KITTI depth metric
https://github.com/nianticlabs/monodepth2/blob/master/evaluate_depth.py#L206

**Comment by hurjunhwa** [comment]
Hi,

We don't do/need any scaling or normalization because our method outputs metric-scale depth on KITTI dataset.
Because we use the same scheme as Monodepth (which uses stereo images for training), scaling is not necessary.
However, when testing our method on other datasets, it does require normalization due to the scale difference.

The other methods including monodepth2 require the median scaling because their methods output depth with unknown scale (if they are trained to do so).

**Comment by russellgeum** [comment]
AAAAAA I got it!!!
Very thanks for your answer
