### ISSUE TITLE
Question about 91875.68 in Eval_SceneFlow_KITTI_Train_Multi

### ISSUE THREAD

**Issue by Yang-Hao-Lin** [visinf/multi-mono-sf#8]
Hi Junhwa
When checking into a class, Eval_SceneFlow_KITTI_Train_Multi,  in your code, I found two weird constants: 91875.68 and 91873.4. 
It does not make sense to me. Why not use  something like "gt_*_mask.sum()" here?

**Comment by hurjunhwa** [comment]
Hi,
It's for averaging the valid GT pixels from the whole 200 test images.
Because each image has the different number of valid pixels, simply averaging the per-frame outlier is not the correct way.
(please refer to the official C++ implementation in the KITTI website).
So, in order to have an equivalent implementation, I use the constants which are the average number of valid pixels per image.

**Comment by Yang-Hao-Lin** [comment]
It helps me a lot! Thank you so much for your quick reply！
